# Generated by Django 4.2.27 on 2025-12-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lego_build', '0010_reviewmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')]),
        ),
    ]
