# Generated by Django 4.2.27 on 2025-12-26 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lego_build', '0011_alter_reviewmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
