# Generated by Django 4.2.27 on 2025-12-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lego_build', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
