# Generated by Django 4.2.27 on 2025-12-23 13:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lego_build', '0003_alter_build_options_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='build',
            new_name='Post',
        ),
    ]
