# Generated by Django 4.2.27 on 2025-12-25 15:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lego_build', '0007_rename_review_reviewmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Build',
        ),
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='post',
            new_name='build',
        ),
    ]
