# Generated by Django 4.2.27 on 2025-12-25 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lego_build', '0009_alter_reviewmodel_options_alter_reviewmodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
