# Generated by Django 4.2.27 on 2025-12-26 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lego_build', '0012_reviewmodel_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_builds', to=settings.AUTH_USER_MODEL),
        ),
    ]
